f=open("people.txt","w")
f.write("priyank - shimla\n")
f.write("neela - delhi\n")
f.write("sashi - jaipur\n")
f.write("sarika - delhi\n")
f.write("deepti - shimla\n")
f.write("harshad - delhi\n")
f.write("trishna - delhi\n")
f.write("pradeep - jaipur\n")
f.write("sekhar - delhi\n")
f.write("nand - delhi\n")
f.write("anoop - delhi\n")
f.write("balwinder - jaipur\n")
f.write("swari-tripura")
f.close()